version: '3.4'

services:
  db-test:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${TODOLIST_DB_PASSWORD}
    ports:
      - 1433:1433
  items-api-integration-test:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=db-test;Initial Catalog=TodoList.ItemsDb.Test;MultipleActiveResultSets=True;Persist Security Info=True;User ID=sa;Password=${TODOLIST_DB_PASSWORD};Trust Server Certificate=true
