services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
  rabbitmq:
    image: rabbitmq:3-management
  items-api:
    build:
      context: .
      dockerfile: src/services/Items/TodoList.Items.API/Dockerfile
    depends_on:
      - db
      - rabbitmq
      - identity-api
  identity-api:
    build:
      context: .
      dockerfile: src/services/Identity/TodoList.Identity.API/Dockerfile
    depends_on:
      - db
      - rabbitmq
  blazor-wasm:
    build:
      context: .
      dockerfile: src/webapps/BlazorWasm/TodoList.Client.Server/Dockerfile
    depends_on:
      - items-api
      - identity-api
  health-monitoring:
    build:
      context: .
      dockerfile: src/webapps/Health/TodoList.Health.Monitoring/Dockerfile
