services:
  db:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${TODOLIST_DB_PASSWORD}
    ports:
      - 1433:1433
    volumes:
      - mssql-data-volume:/var/opt/mssql
  rabbitmq:
    ports:
      - 15672:15672
      - 5672:5672
  items-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
      - ASPNETCORE_HTTPS_PORT=8090
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${TODOLIST_CERTIFICATE_PATH}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${TODOLIST_CERTIFICATE_PASSWORD}
      - ConnectionStrings__DefaultConnection=Data Source=db;Initial Catalog=TodoList.ItemsDb;MultipleActiveResultSets=True;Persist Security Info=True;User ID=sa;Password=${TODOLIST_DB_PASSWORD};Trust Server Certificate=true
      - EventBus__Connection=rabbitmq
      - EventBus__UserName=${TODOLIST_EVENTBUS_USERNAME}
      - EventBus__Password=${TODOLIST_EVENTBUS_PASSWORD}
      - EventBus__BrokerName=${TODOLIST_EVENTBUS_BROKERNAME}
      - EventBus__ClientName=Items
      - EventBus__RetryCount=5
      - Cors__Origins=${TODOLIST_BASE_URL}:8091
      - IdentityUrl=${TODOLIST_BASE_URL}:8092
    ports:
      - 8080:80
      - 8090:443
    volumes:
      - ~/.aspnetcore/https:/https
  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
      - ASPNETCORE_HTTPS_PORT=8092
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${TODOLIST_CERTIFICATE_PATH}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${TODOLIST_CERTIFICATE_PASSWORD}
      - ConnectionStrings__DefaultConnection=Data Source=db;Initial Catalog=TodoList.IdentityDb;MultipleActiveResultSets=True;Persist Security Info=True;User ID=sa;Password=${TODOLIST_DB_PASSWORD};Trust Server Certificate=true
      - EventBus__Connection=rabbitmq
      - EventBus__UserName=${TODOLIST_EVENTBUS_USERNAME}
      - EventBus__Password=${TODOLIST_EVENTBUS_PASSWORD}
      - EventBus__BrokerName=${TODOLIST_EVENTBUS_BROKERNAME}
      - BlazorWasmClientUrl=${TODOLIST_BASE_URL}:8091
      - SendGrid__SenderEmail=${TODOLIST_SENDGRID_SENDEREMAIL}
      - SendGrid__ApiKey=${TODOLIST_SENDGRID_APIKEY}
      - Google__ClientSecret=${TODOLIST_GOOGLE_CLIENTSECRET}
      - Google__ClientId=${TODOLIST_GOOGLE_CLIENTID}
      - Github__ClientSecret=${TODOLIST_GITHUB_CLIENTSECRET}
      - Github__ClientId=${TODOLIST_GITHUB_CLIENTID}
      - Facebook__AppSecret=${TODOLIST_FACEBOOK_APPSECRET}
      - Facebook__AppId=${TODOLIST_FACEBOOK_APPID}
    ports:
      - 8082:80
      - 8092:443
    volumes:
      - ~/.aspnetcore/https:/https
  blazor-wasm:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
      - ASPNETCORE_HTTPS_PORT=8091
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${TODOLIST_CERTIFICATE_PATH}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${TODOLIST_CERTIFICATE_PASSWORD}
      - IdentityUrl=${TODOLIST_BASE_URL}:8092
      - ItemsUrl=${TODOLIST_BASE_URL}:8090
    ports:
      - 8081:80
      - 8091:443
    volumes:
      - ~/.aspnetcore/https:/https
  health-monitoring:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
      - ASPNETCORE_HTTPS_PORT=8093
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${TODOLIST_CERTIFICATE_PATH}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${TODOLIST_CERTIFICATE_PASSWORD}
      - HealthChecks-UI__HealthChecks__0__Name=items-api
      - HealthChecks-UI__HealthChecks__0__Uri=${TODOLIST_BASE_URL}:8090/health
      - HealthChecks-UI__HealthChecks__1__Name=blazor-wasm
      - HealthChecks-UI__HealthChecks__1__Uri=${TODOLIST_BASE_URL}:8091/health
      - HealthChecks-UI__HealthChecks__2__Name=identity-api
      - HealthChecks-UI__HealthChecks__2__Uri=${TODOLIST_BASE_URL}:8092/health
    ports:
      - 8083:80
      - 8093:443
    volumes:
      - ~/.aspnetcore/https:/https

volumes:
  mssql-data-volume:
