services:
  db-test:
    image: mcr.microsoft.com/mssql/server:2019-latest
  items-api-unit-test:
    build:
      context: .
      dockerfile: src/services/Items/TodoList.Items.API/Dockerfile
      target: unit-tests
  items-api-integration-test:
    build:
      context: .
      dockerfile: src/services/Items/TodoList.Items.API/Dockerfile
      target: integration-tests
    depends_on:
      - db-test
